stages:
  - deploy

cache:
  paths:
    - node_modules
    - "packages/*/node_modules"
    - .eslint

deploy:
  stage: deploy
  script:
    - yarn install
    - yarn build
    - mkdir -p /var/www/html/sdi
    - cp -R ./build/. /var/www/html/sdi
  only:
    - staging
  tags:
    - deployment
    - frontend

deployment:
  stage: deployment
  script:
    - yarn install
    - yarn build
    - mkdir -p /var/www/html/sdi
    - cp -R ./build/. /var/www/html/sdi
  only:
    - production
  tags:
    - client
    - production
