stages:
  - deploy

deploy:
  stage: deploy
  script:
    - yarn install
    - yarn build
    - sudo mkdir -p /var/www/html/sdi
    - sudo cp -R ./build/. /var/www/html/sdi
  only:
    - staging
  tags:
    - deployment
    - frontend

