const roles = {
  ADMIN: 'ADMIN',
  REGISTERED_USER: 'REGISTERED_USER',
  EKSEKUTIF: 'EKSEKUTIF',
  MEMBER: 'WALIDATA',
  CONTENT_CREATOR: 'CONTENT_CREATOR',
  CONTENT_EDITOR: 'CONTENT_EDITOR',
  SEKRETARIANT: 'SEKRETARIANT',
  SEKRETARIANT_CREATOR: 'SEKRETARIANT_CREATOR',
  SEKRETARIANT_EDITOR: 'SEKRETARIANT_EDITOR',
  PEMBINA_DATA: 'PEMBINA_DATA',
  PIC_SDGS: 'PIC_SDGS',
  PIC_BAPPENAS: 'PIC_BAPPENAS',
};

export default roles;
