export const TOPIC_LIST = {
  'Pertahanan dan Luar Negeri': ['Pertahanan', 'Luar Negeri'],
  'Ekonomi dan Industri': [
    'Industri',
    'Perdagangan',
    'Pertanian',
    'Perkebunan',
    'Peternakan',
    'Perikanan',
    'Badan Usaha Milik negara',
    'Investasi',
    'Koperasi',
    'Usaha Kecil dan Menengah',
    'Pariwisata',
  ],
  'Pembangunan Daerah': ['Pekerjaan Umum', 'Transmigrasi', 'Transportasi', 'Perumahan', 'Kawasan/Daerah Tertinggal'],
  'Perlindungan Sosial dan Kesehatan': ['Kesehatan', 'Sosial', 'Pemberdayaan Perempuan'],
  'Ketertiban Umum dan Keselamatan': ['Hukum', 'Keamanan', 'Hak Asasi Manusia'],
  'Pendidikan dan Tenaga Kerja': ['Pendidikan', 'Ketenagakerjaan', 'Ilmu Pengetahuan', 'Teknologi', 'Pemuda'],
  'Lingkungan dan Sumber Daya Alam': ['Pertambangan', 'energi', 'Kehutanan', 'Kelautan', 'Lingkungan Hidup'],
  'Budaya dan Agama': ['Agama', 'Kebudayaan', 'Olahraga'],
  'Pemerintahan Umum': [
    'Dalam Negeri',
    'Keuangan',
    'Informasi',
    'Komunikasi',
    'Perencanaan Pembangunan Nasional',
    'Aparatur Negara',
    'Kessekretariatan Negara',
    'Pertanahan',
    'Kependudukan',
  ],
  'Pendukung Umum': ['Kebijakan Pemerintah', 'Manajemen Kegiatan', 'Kewilayahan', 'Data Dukung Lainnya'],
};
